spring:
  redis:
    database: 0
    host: 192.168.1.15
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000



## Redis数据库索引（默认为0）
#  2
#  spring.redis.database=0
#  3
#  # Redis服务器地址
#  4
#  spring.redis.host=192.168.0.24
#  5
#  # Redis服务器连接端口
#  6
#  spring.redis.port=6379
#  7
#  # Redis服务器连接密码（默认为空）
#  8
#  spring.redis.password=
#  9
#  # 连接池最大连接数（使用负值表示没有限制）
#  10
#  spring.redis.pool.max-active=200
#  11
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  12
#  spring.redis.pool.max-wait=-1
#  13
#  # 连接池中的最大空闲连接
#  14
#  spring.redis.pool.max-idle=10
#  15
#  # 连接池中的最小空闲连接
#  16
#  spring.redis.pool.min-idle=0
#  17
#  # 连接超时时间（毫秒）
#  18
#  spring.redis.timeout=1000
